name: Discord PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🚀 Ada PR baru! **${{ github.event.pull_request.title }}** oleh ${{ github.event.pull_request.user.login }}\nLink: ${{ github.event.pull_request.html_url }}"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
